server:
  port: 8083

spring:
  application:
    name: STUDENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      course-service:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3
    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      course-service:
        maxAttempts: 15
        waitDuration: 5000




